### PR TITLE
update(JS): web/javascript/reference/global_objects/json/stringify

### PR DESCRIPTION
**Pull request by undead404**
Оригінальний вміст: [JSON.stringify()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify), [сирці JSON.stringify()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/stringify/index.md)

Нові зміни:
- [mdn/content@3bf9bf8](https://github.com/mdn/content/commit/3bf9bf8a963d64b9990e19e225d1a2c58674e5b9)
- [mdn/content@1ef12f2](https://github.com/mdn/content/commit/1ef12f2e0815d0d285d6027219c987a3e4e228a3)
- [mdn/content@fead533](https://github.com/mdn/content/commit/fead53324d271aa05e93b369966a773bb328c64b)
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)
- [mdn/content@d6f63f6](https://github.com/mdn/content/commit/d6f63f6e41146f459e21046af1c51fadb772de70)

### CODE REVIEW

**Review by AdriandeCita — CHANGES_REQUESTED** [review]
Є свіжі зміни:
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)

**Comment by undead404** [comment]
Оновлено

**Comment by undead404** [comment]
Без змін

**Review by AdriandeCita — CHANGES_REQUESTED** [review]
Свіжі:
- [mdn/content@3bf9bf8](https://github.com/mdn/content/commit/3bf9bf8a963d64b9990e19e225d1a2c58674e5b9)

**Comment by undead404** [comment]
Оновлено: https://github.com/mdn/content/commit/3bf9bf8a963d64b9990e19e225d1a2c58674e5b9

**Review by AdriandeCita — APPROVED** [review]

**Pull request merged**
