### PR TITLE
update(css): /Web/CSS/Specificity

### PR DESCRIPTION
**Pull request by AdriandeCita**
Original content: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

нові зміни: [6e3f9b7](https://github.com/mdn/content/commit/6e3f9b7d379f212bc0a5cfb4622d83234f1a5607), [d779126](https://github.com/mdn/content/commit/d7791268eabae921e32eedcbc3a6b6606504a1f0), [56cef13](https://github.com/mdn/content/commit/56cef13241e8d9e9ba980840e28202152e099f36), [5b0f300](https://github.com/mdn/content/commit/5b0f300d94517cc24e1e0524a6a2304a9c1f989b)

### CODE REVIEW

**Review by undead404 — APPROVED** [review]

**Comment by undead404** [comment]
Updated with:
* https://github.com/mdn/content/commit/64552be5038f76e3e3046b856f50b8fd8f2293a5
* https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e

**Comment by undead404** [comment]
Up to date.

**Comment by AdriandeCita** [comment]
Цей я перестворю, бо тут трохи забагато змін в скоупі набралось

**Comment by AdriandeCita** [comment]
Re-created this PR here https://github.com/webdoky/content/pull/336, containing changes related to "Specificity" page

**Pull request closed without merging**
