### PR TITLE
update(JS): web/javascript/reference/global_objects/string

### PR DESCRIPTION
**Pull request by undead404**
Оригінальний вміст: [String@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String), [сирці String@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/index.md)

Нові зміни:
- [mdn/content@a2668bb](https://github.com/mdn/content/commit/a2668bbb974eac9427091009dc48da2c33707251)
- [mdn/content@8cd16f0](https://github.com/mdn/content/commit/8cd16f08b673f911574f65f4cc60944a9329aea7)
- [mdn/content@b01d1a6](https://github.com/mdn/content/commit/b01d1a6b1ed153eaf24e980da825349c9a5b0cb8)
- [mdn/content@aa699f7](https://github.com/mdn/content/commit/aa699f7c359f178c8bc4ad691bf0e8ccb7fc4d57)
- [mdn/content@1ef12f2](https://github.com/mdn/content/commit/1ef12f2e0815d0d285d6027219c987a3e4e228a3)
- [mdn/content@2d6d6a1](https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c)
- [mdn/content@c362aeb](https://github.com/mdn/content/commit/c362aebc2e4e7600be3a8ce6e97aaa8f7bad8810)
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)
- [mdn/content@a6785a8](https://github.com/mdn/content/commit/a6785a8e4ddad80069acf2de418235c0640688e7)

### CODE REVIEW

**Review by AdriandeCita — CHANGES_REQUESTED** [review]
Є свіжі зміни:
- [mdn/content@2d6d6a1](https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c)
- [mdn/content@c362aeb](https://github.com/mdn/content/commit/c362aebc2e4e7600be3a8ce6e97aaa8f7bad8810)
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)

**Comment by undead404** [comment]
Оновлено

**Comment by undead404** [comment]
Без змін.

**Review by AdriandeCita — CHANGES_REQUESTED** [review]
Свіжі
- [mdn/content@8cd16f0](https://github.com/mdn/content/commit/8cd16f08b673f911574f65f4cc60944a9329aea7)
- [mdn/content@b01d1a6](https://github.com/mdn/content/commit/b01d1a6b1ed153eaf24e980da825349c9a5b0cb8)

**Comment by undead404** [comment]
Оновлено:
* https://github.com/mdn/content/commit/b01d1a6b1ed153eaf24e980da825349c9a5b0cb8
* https://github.com/mdn/content/commit/8cd16f08b673f911574f65f4cc60944a9329aea7
* https://github.com/mdn/content/commit/a2668bbb974eac9427091009dc48da2c33707251

**Review by AdriandeCita — APPROVED** [review]

**Pull request merged**
