### PR TITLE
update(Glossary): glossary/baseline/compatibility

### PR DESCRIPTION
**Pull request by undead404**
Оригінальний вміст: [База (сумісність)@MDN](https://developer.mozilla.org/en-us/docs/Glossary/Baseline/Compatibility), [сирці База (сумісність)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/glossary/baseline/compatibility/index.md)

Нові зміни:
- [#26912 Glossary: Baseline (#34385)](https://github.com/mdn/content/commit/70aa041ebd7e31df76818bc8459f60659fe94c0c)
- [Baseline glossary entry: mention accessibility and other considerations (#33515)](https://github.com/mdn/content/commit/0b6014227876b84599512deab197e8c65018850f)
- [Define how long widely available features are supported for (#33443)](https://github.com/mdn/content/commit/f3fbc8cc2c099ba4a050573cd92d1bd4db36cae0)
- [Add badges to Baseline glossary page (#30800)](https://github.com/mdn/content/commit/d14b5a927958ec1ab9737f2f9fce0761a4c95c75)
- [Revise the Baseline glossary entry to reflect the new definition (#30769)](https://github.com/mdn/content/commit/234df545af685b3cf53274b8de8f14ac45af750a)

### CODE REVIEW

**Comment by AdriandeCita** [comment]
Blocked until the actual widget is implemented https://github.com/webdoky/content/issues/2594

**Comment by undead404** [comment]
Залежить від:
* https://github.com/webdoky/platform-next/pull/61

**Review by undead404 — COMMENTED** [review]
Relevant?

**Review by alinkedd — COMMENTED** [review]
Relevant?

**Pull request merged**
