### PR TITLE
translation(JS): web/javascript/reference/statements/try...catch

### PR DESCRIPTION
**Pull request by undead404**
Оригінальний вміст: [try...catch@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Statements/try...catch), [сирці try...catch@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/try...catch/index.md)

### CODE REVIEW

**Comment by undead404** [comment]
Оновлено

**Comment by undead404** [comment]
Up to date

**Comment by undead404** [comment]
Без змін.

**Comment by undead404** [comment]
Оновлено: https://github.com/mdn/content/commit/3ff45899bbb6c1e82abfc8b6a88703bd09e6e685#diff-757dad4ee31cd782174bf5bf6f4c349c23f1c63569558dbc4a83b5fcce9e7002

**Comment by undead404** [comment]
Без змін.

**Comment by undead404** [comment]
Оновлено:
* https://github.com/mdn/content/blob/1533276490d15cff6ddcd201fc05562180058a99/files/en-us/web/javascript/reference/statements/try...catch/index.md

**Review by AdriandeCita — APPROVED** [review]

**Pull request merged**
