### PR TITLE
update(HTML): web/html/element/a

### PR DESCRIPTION
**Pull request by undead404**
Оригінальний вміст: [&lt;a>: Якірний елемент@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/a), [сирці &lt;a>: Якірний елемент@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md)

Нові зміни:
- [mdn/content@7b36c6f](https://github.com/mdn/content/commit/7b36c6f4be21b3f10a6fa58c41428a807de4160c)
- [mdn/content@f310b6e](https://github.com/mdn/content/commit/f310b6e83adaaac0ae0e38f9e5053240b37b720b)
- [mdn/content@96a3f02](https://github.com/mdn/content/commit/96a3f02a83c5624f2210f602eb2220831e86cd01)
- [mdn/content@4a2b6ca](https://github.com/mdn/content/commit/4a2b6cafbf9bc5b006eedbdf0e9fdf2c8626d5b6)
- [mdn/content@1a9baa7](https://github.com/mdn/content/commit/1a9baa7353ead965d9221d9edbe30f45a711382b)
- [mdn/content@7cc4c9d](https://github.com/mdn/content/commit/7cc4c9d83ea081ff9214716564be6e9c34515db7)
- [mdn/content@6133c0d](https://github.com/mdn/content/commit/6133c0d450f3c28d338c3af9a002fba567338f31)
- [mdn/content@d05f7e9](https://github.com/mdn/content/commit/d05f7e910c03168355f5ac96ee3724edd76573f4)

### CODE REVIEW

**Comment by undead404** [comment]
Оновлено

**Comment by undead404** [comment]
Оновлено

**Comment by undead404** [comment]
Оновлено

**Review by AdriandeCita — APPROVED** [review]

**Review by AdriandeCita — CHANGES_REQUESTED** [review]
Іще невеличкі зміни https://github.com/mdn/content/commit/7b36c6f4be21b3f10a6fa58c41428a807de4160c

**Comment by undead404** [comment]
Оновлено

**Review by AdriandeCita — APPROVED** [review]

**Pull request merged**
